#!/bin/sh -e

libdir="/root/openGauss-third_party/dependency/nghttp2/nghttp2/lib"
if [ -d "$libdir/.libs" ]; then
    libdir="$libdir/.libs"
fi

export CGO_CFLAGS="-I/root/openGauss-third_party/dependency/nghttp2/nghttp2/lib/includes -I/root/openGauss-third_party/dependency/nghttp2/nghttp2/lib/includes "
export CGO_CPPFLAGS=""
export CGO_LDFLAGS="-L$libdir "
export LD_LIBRARY_PATH="$libdir"
export DYLD_LIBRARY_PATH="$libdir"
export GODEBUG=cgocheck=0
"$@"
